## 3.1 시리즈 소개

In [1]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
from pandas import Series

## 3.2 시리즈 생성

In [5]:
from pandas import Series

data = [10, 20, 30]
s = Series(data)
print(s)


0    10
1    20
2    30
dtype: int64


In [6]:
from pandas import Series
import numpy as np

data = np.arange(5)
s = Series(data)
print(s)

0    0
1    1
2    2
3    3
4    4
dtype: int64


In [7]:
data = ["시가", "고가"]
s = Series(data)
print(s)

0    시가
1    고가
dtype: object


In [8]:
s = Series(['samsung', 81000])
print(s)

0    samsung
1      81000
dtype: object


## 3.3 시리즈 인덱스

In [9]:
data = [1000, 2000, 3000]
s = Series(data)
print(s.index)
print(s.index.to_list())

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]


In [10]:
data = [1000, 2000, 3000] 
s = Series(data)
s.index = ["메로나", "구구콘", "하겐다즈"]
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [11]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]

s = Series(data, index)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [13]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]

s = Series(index=index, data=data)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [14]:
k = [1000, 2000, 3000]
v = ["메로나", "구구콘", "하겐다즈"]

s = Series(data=v, index=k)
print(s)

1000     메로나
2000     구구콘
3000    하겐다즈
dtype: object


In [15]:
s = Series(data, index)
s = Series(data, index=index)
s = Series(data=data, index=index)
s = Series(index=index, data=data)

In [16]:
data = [1000, 2000, 3000]
index = ['메로나', '구구콘', '하겐다즈']
s = Series(data=data, index=index)
s2 = s.reindex(["메로나", "비비빅", "구구콘"])
print(s2)

메로나    1000.0
비비빅       NaN
구구콘    2000.0
dtype: float64


In [17]:
print(s2.fillna(0))

메로나    1000.0
비비빅       0.0
구구콘    2000.0
dtype: float64


In [18]:
print(s.reindex(["메로나", "비비빅", "구구콘"], fill_value=0))

메로나    1000
비비빅       0
구구콘    2000
dtype: int64


In [19]:
price = [42500, 42550, 41800, 42550, 42650]
date = ["2019-a05-31", "2019-05-30", "2019-05-29", "2019-05-28", "2019-05-27"]
s = Series(price, date)
print(s)

2019-a05-31    42500
2019-05-30     42550
2019-05-29     41800
2019-05-28     42550
2019-05-27     42650
dtype: int64


In [20]:
data = {
    "2019-05-31" : 42500,
    "2019-05-30" : 42550,
    "2019-05-29" : 41800,
    "2019-05-28" : 42550,
    "2019-05-27" : 42650
}
s = Series(data)

In [21]:
print(s.index)
print(s.index.dtype)

Index(['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27'], dtype='object')
object


In [22]:
print(s.values)

[42500 42550 41800 42550 42650]


## 3.4 시리즈 인덱싱

In [23]:
data = [1000, 2000, 3000]
s = Series(data=data)

print(s.iloc[0])
print(s.iloc[1])
print(s.iloc[2])
print(s.iloc[-1])

1000
2000
3000
3000


In [24]:
print(s.loc[0])
print(s.loc[1])
print(s.loc[2])
# print(s.loc[-1])   # 에러

1000
2000
3000


In [26]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=data, index=index)
 
print(s.iloc[0])
print(s.loc['메로나'])

1000
1000


In [27]:
print(s['메로나'])
print(s[0])

1000
1000


C:\Users\edukd\AppData\Local\Temp\ipykernel_5128\870197432.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


In [25]:
s1 = Series([10, 20, 30])
s2 = Series([10, 20, 30], index=[1, 2, 3])
print(s1[0])
# print(s2[0])    # 에러

10


In [26]:
s3 = Series([10, 20, 30], index=['a', 'b', 'c'])
print(s3[0])

10


In [71]:
print(s3.index[ 0 ])
print(s3.index[ -1 ])

a
c


## 3.5 시리즈 슬라이싱

In [40]:
import pandas as pd

# 1) 간단한 Series 만들기
# TODO: [10, 20, 30] 데이터를 담은 Series를 만들어보세요.
s = pd.Series([10, 20, 30])
print(s)

# 2) 인덱스를 지정해보기
# TODO: ['a', 'b', 'c'] 를 인덱스로 붙여서 Series를 다시 만들어보세요.
s2 = pd.Series(index=['a', 'b', 'c'], data=[10, 20, 30] )
print(s2)

# 3) 특정 값 선택
# TODO: s2에서 'b' 인덱스의 값을 선택해보세요.
val_b = s2['b']
print(val_b)

# 4) 조건 연산
# TODO: s2에서 값이 15보다 큰 항목만 골라보세요.
cond = s2 > 15
print(s2.loc[cond])

# 5) 메서드 사용
# TODO: s2의 합계와 평균을 구해보세요.
sum_val = s2.sum()
mean_val = s2.mean()
print(sum_val)
print(mean_val)


0    10
1    20
2    30
dtype: int64
a    10
b    20
c    30
dtype: int64
20
b    20
c    30
dtype: int64
60
20.0


In [28]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=data, index=index)

print(s.iloc[0:2])

메로나    1000
구구콘    2000
dtype: int64


In [29]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=data, index=index)

print(s.loc['메로나':'구구콘'])

메로나    1000
구구콘    2000
dtype: int64


In [30]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=data, index=index)

indice = [0, 2]
print(s.iloc[ indice ])
print(s.iloc[ [0, 2] ])

메로나     1000
하겐다즈    3000
dtype: int64
메로나     1000
하겐다즈    3000
dtype: int64


In [32]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=data, index=index)

indice = ["메로나", "하겐다즈"]
print(s.loc[ indice ])
print(s.loc[ ["메로나", "하겐다즈"] ])

메로나     1000
하겐다즈    3000
dtype: int64
메로나     1000
하겐다즈    3000
dtype: int64


## 3.6 시리즈 수정/추가/삭제

In [46]:
import pandas as pd

# 연습용 Series (재고 수량)
s = pd.Series([10, 20, 15], index=["apple", "banana", "cherry"])
print("원본 Series:\n", s)

# =======================
# 1) 수정
# =======================
# TODO 1-1: 'banana'의 값을 25로 수정하세요.
s = s.rename(index={"banana" : 25})

# TODO 1-2: 여러 개 수정하기 → 'apple'=12, 'cherry'=18로 수정하세요.
s = s.rename(index={"apple" : 12, "cherry" : 18})

# =======================
# 2) 추가
# =======================
# TODO 2-1: 'date'=9를 새로 추가하세요.
s['date'] = 9
print("원본 Series:\n", s)

# TODO 2-2: 여러 개 추가하기 → 'elderberry'=7, 'fig'=11 추가
s['elderberry'] = 7
s['fig'] = 11
# =======================
# 3) 삭제
# =======================
# TODO 3-1: 'banana' 항목을 삭제한 새로운 Series를 만들어보세요.
print(s)
v1 = pd.Series(index=["apple", "cherry"], data= [10, 15])
# TODO 3-2: ['apple','fig'] 두 개 항목을 한 번에 삭제해보세요.
s = s.reindex(["date","elderberry"])
s


원본 Series:
 apple     10
banana    20
cherry    15
dtype: int64
원본 Series:
 12      10
25      20
18      15
date     9
dtype: int64
12            10
25            20
18            15
date           9
elderberry     7
fig           11
dtype: int64


date          9
elderberry    7
dtype: int64

In [45]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=data, index=index)

s.loc['메로나'] = 500          # 값 수정
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
dtype: int64


In [46]:
s.iloc[0] = 500            # iloc 연산 사용
s['메로나'] = 500          # [ ] 기호 사용

In [47]:
s.loc['비비빅'] = 500          # 값 추가 
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [42]:
print(s.drop('메로나'))

구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [48]:
s = s.drop('메로나')
print(s)

구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [49]:
s

구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64

In [51]:
s.iloc[ : 2] = 100
print(s)

구구콘     100
하겐다즈    100
비비빅     500
dtype: int64


## 3.7 시리즈 연산

In [47]:
철수 = Series([10, 20, 30], index=['NAVER', 'SKT', 'KT'])
영희 = Series([10, 30, 20], index=['SKT', 'KT', 'NAVER'])
가족 = 철수 + 영희
print(가족)

KT       60
NAVER    30
SKT      30
dtype: int64


In [48]:
print(철수 * 10)

NAVER    100
SKT      200
KT       300
dtype: int64


In [51]:
high = Series([42800, 42700, 42050, 42950, 43000])
low = Series([42150, 42150, 41300, 42150, 42350])

diff = high - low
print(diff)

0    650
1    550
2    750
3    800
4    650
dtype: int64


In [52]:
print(diff.max())
print(max(diff))

800
800


In [53]:
date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = Series([42800, 42700, 42050, 42950, 43000], index=date)
low = Series([42150, 42150, 41300, 42150, 42350] , index=date)
diff = high - low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [54]:
max_idx = 0
max_val = 0

for i in range(len(diff)):
    if diff[i] > max_val:
        max_val = diff[i]
        max_idx = i

print(max_idx)
print(diff.index[max_idx])    

3
6/4


C:\Users\edukd\AppData\Local\Temp\ipykernel_5128\1955845044.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if diff[i] > max_val:
C:\Users\edukd\AppData\Local\Temp\ipykernel_5128\1955845044.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  max_val = diff[i]


In [55]:
print(diff.idxmax())
print(diff.idxmin())

6/4
6/2


In [56]:
date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = Series([42800, 42700, 42050, 42950, 43000], index=date)
low = Series([42150, 42150, 41300, 42150, 42350] , index=date)
profit = high / low
print(profit)

6/1    1.015421
6/2    1.013049
6/3    1.018160
6/4    1.018980
6/5    1.015348
dtype: float64


In [ ]:
print( profit.cumprod( ) ) 

6/1    1.015421
6/2    1.028671
6/3    1.047351
6/4    1.067230
6/5    1.083610
dtype: float64


In [57]:
print( profit.cumprod( ).iloc[ -1 ] )

1.0836101509172456


In [58]:
data = {
    "삼성전자": "전기,전자",
    "LG전자": "전기,전자",
    "현대차": "운수장비",
    "NAVER": "서비스업",
    "카카오": "서비스업"
}
s = Series(data)

In [59]:
print(s.unique())

['전기,전자' '운수장비' '서비스업']


## 3.8 시리즈와 맵

In [60]:
from pandas import Series
s = Series(["1,234", "5,678", "9,876"])
print( int(s) )

TypeError: cannot convert the series to <class 'int'>

In [61]:
def remove_comma(x) :
    print(x, 'in function')
    return x

s = Series(["1,234", "5,678", "9,876"])
result = s.map(remove_comma)
print(result)

1,234 in function
5,678 in function
9,876 in function
0    1,234
1    5,678
2    9,876
dtype: object


In [62]:
from pandas import Series

def remove_comma(x) :
    return int(x.replace(",", ""))

s = Series(["1,234", "5,678", "9,876"])
result = s.map(remove_comma)
print(result)

0    1234
1    5678
2    9876
dtype: int64


In [63]:
def is_greater_than_5000(x):
    if x > 5000:
        return "크다"
    else:
        return "작다"

s = Series([1234, 5678, 9876])
s = s.map(is_greater_than_5000)
print(s)

0    작다
1    크다
2    크다
dtype: object


## 3.9 시리즈 필터링

In [65]:
from pandas import Series

data = [42500, 42550, 41800, 42550, 42650]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
s = Series(data=data, index=index)
cond = s > 42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [66]:
print(s[cond])

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [67]:
close = [42500, 42550, 41800, 42550, 42650]
open = [42600, 42200, 41850, 42550, 42500]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']

open = Series(data=open, index=index)
close = Series(data=close, index=index)

cond = close > open
print(cond)

2019-05-31    False
2019-05-30     True
2019-05-29    False
2019-05-28    False
2019-05-27     True
dtype: bool


In [68]:
cond = close > open
print(close[cond])

2019-05-30    42550
2019-05-27    42650
dtype: int64


In [69]:
print(close[close > open])

2019-05-30    42550
2019-05-27    42650
dtype: int64


In [70]:
print(close.index[close > open])
print(close[close > open].index)

Index(['2019-05-30', '2019-05-27'], dtype='object')
Index(['2019-05-30', '2019-05-27'], dtype='object')


In [71]:
close = [42500, 42550, 41800, 42550, 42650]
open = [42600, 42200, 41850, 42550, 42500]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']

open = Series(data=open, index=index)
close = Series(data=close, index=index)
diff = close - open
print(diff[close > open])

2019-05-30    350
2019-05-27    150
dtype: int64


## 3.10 정렬 및 순위

In [73]:
from pandas import Series

data = [3.1, 2.0, 10.1, 5.1]
index = ['000010', '000020', '000030', '000040']
s = Series(data=data, index=index)
print(s)

# 정렬 (오름차순)
s1 = s.sort_values()
print(s1)

# 정렬 (내림차순)
s2 = s.sort_values(ascending=False)
print(s2)

000010     3.1
000020     2.0
000030    10.1
000040     5.1
dtype: float64
000020     2.0
000010     3.1
000040     5.1
000030    10.1
dtype: float64
000030    10.1
000040     5.1
000010     3.1
000020     2.0
dtype: float64


In [74]:
data = [3.1, 2.0, 10.1, 3.1]
index = ['000010', '000020', '000030', '000040']
s = Series(data=data, index=index)
print(s.rank())

000010    2.5
000020    1.0
000030    4.0
000040    2.5
dtype: float64


In [97]:
import pandas as pd

# 연습용 데이터 (과일 가격)
s = pd.Series([1200, 2500, 1800, 600, 2200],
              index=["apple", "banana", "cherry", "date", "elderberry"])
# print("원본 Series:\n", s)

# =======================
# 1) 인덱싱
# =======================
# TODO 1-1: 'banana' 가격을 선택하세요.
v1 = s['banana']
# print(v1)

# TODO 1-2: ['apple','cherry'] 선택하세요.
v2 = s.loc[['apple','cherry']]
# print(v2)
# =======================
# 2) 슬라이싱
# =======================
# TODO 2-1: 'banana'부터 'date'까지 라벨로 슬라이싱하세요.
v3 = s.loc["banana" : "date"]
# print(v3)
# TODO 2-2: 처음 3개만 iloc으로 선택하세요.
v4 = s.iloc[:3]
# print(v4)

# =======================
# 3) 수정 / 추가 / 삭제
# =======================
# TODO 3-1: 'banana' 가격을 2600으로 수정하세요.
s['banana'] = 2600

# TODO 3-2: 'fig'=1500을 추가하세요.
s['fig'] = 1500

# TODO 3-3: 'date'를 삭제해 새로운 Series v5를 만드세요.
v5 = s.drop('date')
# print(v5)

# =======================
# 4) 연산
# =======================
# TODO 4-1: 모든 값에 +100을 더하세요.
v6 = v5 + 100
# print(v6)
# TODO 4-2: 모든 값에 10% 증가(×1.1)를 적용하세요.
v7 = v6 * 1.1
# print(v7)
# =======================
# 5) map
# =======================
# TODO 5-1: 값이 1000 이상이면 "HIGH", 아니면 "LOW"로 변환하세요.
for i in range(len(v7)):
    if v7[i] >= 1000:
        v7[i] = "HIGH"
    else:
        v7[i] = "LOW"
print(v7)
# =======================
# 6) 필터링
# =======================
# TODO 6-1: 값이 1500 이상인 항목만 선택하세요.
cond = v6 >= 1500
v8 = v6[cond]
# print(v8)

# TODO 6-2: 인덱스가 ['apple','fig']인 항목만 선택하세요.
v9 = v6[['apple','fig']]
# print(v9)
# =======================
# 7) 정렬 및 순위
# =======================
# TODO 7-1: 값 기준 오름차순 정렬하세요.
v10 = s.sort_values(ascending=True)
print(v10)
# TODO 7-2: 값 기준 순위를 매겨보세요.
v11 = v10.rank()
print(v11)


apple         HIGH
banana        HIGH
cherry        HIGH
elderberry    HIGH
fig           HIGH
dtype: object
date           600
apple         1200
fig           1500
cherry        1800
elderberry    2200
banana        2600
dtype: int64
date          1.0
apple         2.0
fig           3.0
cherry        4.0
elderberry    5.0
banana        6.0
dtype: float64


C:\Users\edukd\AppData\Local\Temp\ipykernel_5128\2667592116.py:55: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if v7[i] >= 1000:
C:\Users\edukd\AppData\Local\Temp\ipykernel_5128\2667592116.py:56: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  v7[i] = "HIGH"
C:\Users\edukd\AppData\Local\Temp\ipykernel_5128\2667592116.py:56: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'HIGH' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  v7[i] = "HIGH"


In [112]:
d1 = pd.Series([10, 24, 50, 58, 25], index=["엄마는외계인", "아몬드봉봉", "레인보우샤베트", "슈팅스타", "초코"])
d2 = pd.Series([13, 30, 27, 82, 40], index=["엄마는외계인", "아몬드봉봉", "레인보우샤베트", "슈팅스타", "초코"])
d3 = pd.Series([10, 23, 38, 29, 14], index=["엄마는외계인", "아몬드봉봉", "레인보우샤베트", "슈팅스타", "초코"])
d4 = pd.Series([18, 24, 50, 58, 25], index=["엄마는외계인", "아몬드봉봉", "레인보우샤베트", "슈팅스타", "초코"])
d5 = pd.Series([12, 18, 38, 3, 25], index=["엄마는외계인", "아몬드봉봉", "레인보우샤베트", "슈팅스타", "초코"])
d6 = pd.Series([11, 20, 4, 7, 25], index=["엄마는외계인", "아몬드봉봉", "레인보우샤베트", "슈팅스타", "초코"])
d7 = pd.Series([10, 30, 23, 9, 25], index=["엄마는외계인", "아몬드봉봉", "레인보우샤베트", "슈팅스타", "초코"])
price = pd.Series([3000, 2500, 1700, 6000, 3300], index=["엄마는외계인", "아몬드봉봉", "레인보우샤베트", "슈팅스타", "초코"])
total_sales = d1 + d2 + d3 + d4 + d5 + d6 + d7
list = [d1, d2, d3, d4, d5, d6, d7]

print(total_sales)
print("\n")
total_revenue = total_sales * price
print(total_revenue)
print("\n")
max_sales = 0
max_index = 0
for i in range(len(list)):
    if list[i].sum() > max_sales:
        max_sales = list[i].sum()
        max_index = i
print(list[max_index])


엄마는외계인      84
아몬드봉봉      169
레인보우샤베트    230
슈팅스타       246
초코         179
dtype: int64


엄마는외계인      252000
아몬드봉봉       422500
레인보우샤베트     391000
슈팅스타       1476000
초코          590700
dtype: int64


엄마는외계인     13
아몬드봉봉      30
레인보우샤베트    27
슈팅스타       82
초코         40
dtype: int64


In [1]:
from pandas import Series
import numpy as np

index = ['수박바','죠스바','월드콘','메로나']
p = [1000,1200,2000,1500]
q = np.random.randint(100, size=(7,4))
print(q)

# 1) 맛별 총판매량
total_ea = q.sum(axis=0)
s2 = Series(data = total_ea, index=index)

# 2) 맛별 총수익
total_p = total_ea * p
s3 = Series(data=total_p, index=index)

# 3) 날짜별 총판매량 (행 합계)
day_totals = q.sum(axis=1)
s_day = Series(data=day_totals, index=[f"day{i+1}" for i in range(7)])

# 4) 가장 많이 팔린 날짜
best_day = s_day.idxmax()
best_units = s_day.max()

print("맛별 총판매량\n", s2)
print("\n맛별 총수익\n", s3)
print("\n날짜별 총판매량\n", s_day)
print(f"\n🗓️ 가장 많이 팔린 날짜: {best_day} (총 {best_units}개)")

[[64 55 30 74]
 [67 65 20 67]
 [75 99 78 45]
 [93 90 88 79]
 [57 46 33  9]
 [48  0 49 71]
 [53 35  6 58]]
맛별 총판매량
 수박바    457
죠스바    390
월드콘    304
메로나    403
dtype: int64

맛별 총수익
 수박바    457000
죠스바    468000
월드콘    608000
메로나    604500
dtype: int64

날짜별 총판매량
 day1    223
day2    219
day3    297
day4    350
day5    145
day6    168
day7    152
dtype: int64

🗓️ 가장 많이 팔린 날짜: day4 (총 350개)


In [19]:
# ============================================
# 일주일 베스트 종목 & 손익
#
# 목표:
#   1) 종목별 7일 누적 "가격변화"
#   2) 종목별 7일 누적 "손익(= 보유수량 × 가격변화)"
#   3) 가장 손익이 큰 날짜
#
# 학습 포인트:
#   - NumPy 합계: changes.sum(axis=0/1)
#       * axis=0 → 열(종목) 방향 합  → "종목별" 합계
#       * axis=1 → 행(날짜) 방향 합  → "날짜별" 합계
#   - 브로드캐스팅: (changes * shares.values)  # (7×4) * (4,) → (7×4)
#   - Series/배열 최대값 라벨: idxmax()
# ============================================

from pandas import Series
import numpy as np

# ----- 0) 예시 데이터 준비 (실행만 하면 됨) -----
#티커 = 주식별명 (숫자/알파벳)          
tickers = ['삼성전자','LG전자','현대차','NAVER']   

shares  = Series([50, 30, 20, 15], index=tickers, name="보유수량")  # 보유수량(주)
days    = [f"day{i+1}" for i in range(7)]                      # 7일

# 하루 가격변화(원): 7일 × 4종목 (음수/양수 가능)
changes = np.random.randint(-500, 501, size=(7, 4))
# changes: 행=날짜, 열=종목

# ===========================================================
# 1) 종목별 7일 누적 "가격변화"
#    - NumPy로 열 합계(axis=0)를 구한 뒤, 종목 라벨로 Series 생성
# ===========================================================

# TODO-1A: changes.sum(axis=0)로 종목별 누적 가격변화(길이 4) 구하기
delta_by_ticker_np = changes.sum(axis=0)

# TODO-1B: 위 결과를 종목 라벨(tickers)로 가지는 Series로 만들기
delta_by_ticker = Series(delta_by_ticker_np, index=tickers, name="누적가격변화")

print("📊 종목별 7일 누적 가격변화(원)\n", delta_by_ticker, "\n")


# ===========================================================
# 2) 종목별 7일 누적 "손익(원)"
#    - 방법 A(Series×Series): delta_by_ticker * shares
#    - 방법 B(브로드캐스팅): (changes * shares.values).sum(axis=0)
#      * 둘 중 하나만 해도 되고, 두 방법을 비교해도 좋아요.
# ===========================================================


# TODO-2A: Series×Series 곱으로 종목별 누적 손익 계산
pnl_by_ticker = delta_by_ticker * shares        # 예) delta_by_ticker * shares

# (선택) TODO-2B: 브로드캐스팅으로 동일 값 확인
daily_pnl_matrix = changes * shares.values          # (7×4)
pnl_by_ticker_b = daily_pnl_matrix.sum(axis=0)      # (4,)
pnl_by_ticker_b = Series(pnl_by_ticker_b, index=tickers)


# ===========================================================
# 3) 날짜별 "하루 손익(원)"과 1등 날짜
#    - 브로드캐스팅으로 하루 손익 행벡터(길이 7)를 만든 뒤 Series로 변환
#    - 가장 손익이 큰 날짜: idxmax()
# ===========================================================

# TODO-3A: 하루 손익(행 합계) 계산
#   힌트: daily_pnl_matrix = changes * shares.values    # (7×4)
#        day_pnl_np = daily_pnl_matrix.sum(axis=1)      # (7,)
#        day_pnl = Series(day_pnl_np, index=days, name="일별손익")
day_pnl_np = daily_pnl_matrix.sum(axis=1)
day_pnl = Series(day_pnl_np, index=days, name="일별손익")

# TODO-3B: 가장 손익이 큰 날짜 라벨과 손익값
#   힌트: best_day = day_pnl.idxmax()
#        best_pnl = day_pnl.max()
best_day = day_pnl.idxmax()
best_pnl = day_pnl.max()
print(f"가장 손익이 큰 날짜는 {best_day}이고, 그 손익값은 {best_pnl}이다.")


# ===========================================================
# (추가 연습) 선택 과제
#   - 가장 손익이 큰 종목 라벨: pnl_by_ticker.idxmax()
#   - 가장 손익이 작은 종목 라벨: pnl_by_ticker.idxmin()
#   - 누적 손익 검증: pnl_by_ticker.sum() == day_pnl.sum()
#   - 누적 가격변화가 0인 종목만 필터링해보기 (== 0)
# ===========================================================

# TODO-추가1: best_ticker = pnl_by_ticker.idxmax()
# TODO-추가2: worst_ticker = pnl_by_ticker.idxmin()
# TODO-추가3: 검증 프린트
# print("검증:", pnl_by_ticker.sum(), "==", day_pnl.sum())
# TODO-추가4: zero_delta = delta_by_ticker[ delta_by_ticker == 0 ]
print(pnl_by_ticker, "\n")
print(day_pnl)
for i in tickers:
    if delta_by_ticker[i] == 0:
        print(f"{i}는 가격 변동이 없습니다!")
best_ticker = pnl_by_ticker.idxmax()
worst_ticker = pnl_by_ticker.idxmin()
print(f"가장 좋은 주식은 {best_ticker}이다.")
print(f"가장 안좋은 주식은 {worst_ticker}이다.")
print(pnl_by_ticker.sum() == day_pnl.sum())

📊 종목별 7일 누적 가격변화(원)
 삼성전자    -263
LG전자    -778
현대차     -491
NAVER    -48
Name: 누적가격변화, dtype: int64 

가장 손익이 큰 날짜는 day5이고, 그 손익값은 10750이다.
삼성전자    -13150
LG전자    -23340
현대차      -9820
NAVER     -720
dtype: int64 

day1     3550
day2   -29555
day3   -24200
day4     1115
day5    10750
day6    -7760
day7     -930
Name: 일별손익, dtype: int64
가장 좋은 주식은 NAVER이다.
가장 안좋은 주식은 LG전자이다.
True
