#### 1. Import NumPy as np

In [2]:
import numpy as np

#### 2. 10개의 0으로 채워진 배열 생성 

In [2]:
# 결과
# array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. 10개의 1로 채워진 배열 생성

In [3]:
# 결과
# array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. 10개의 5로 채워진 배열 생성

In [4]:
# 결과
# array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [48]:
np.full(10, 5)
np.zeros(10) + 5
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. 1부터 10까지 정수 배열 생성

In [5]:
# 결과
# array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 6. 1부터 100까지 짝수로 이루어진 배열 생성


In [6]:
# 결과
# array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
#         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
#         54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
#         80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [5]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

#### 7. 0부터 8까지 숫자로 이루어진 3x3배열 생성

In [7]:
# 결과
# array([[0, 1, 2],
#        [3, 4, 5],
#        [6, 7, 8]])

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. 5x5 단위행렬 생성

In [8]:
# 결과
# array([[1., 0., 0., 0., 0.],
#        [0., 1., 0., 0., 0.],
#        [0., 0., 1., 0., 0.],
#        [0., 0., 0., 1., 0.],
#        [0., 0., 0., 0., 1.]])

In [50]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 9. 0~1 사이의 랜덤수 생성

In [9]:
# 결과예시
# 0.5163986277024462

In [11]:
np.random.random()

0.4231759192952691

#### 9. 1부터 5 사이의 랜덤수 생성(5 포함)


In [10]:
# 결과예시
# 5

#### 10. 표준정규분포를 따르는 100개의 랜덤수로 이루어진 배열 생성

In [11]:
# 결과예시
# array([ 2.50338201,  0.99905888,  0.48439554,  0.1114564 ,  0.3866839 ,
#         0.80955338,  0.46150244,  1.19488841,  1.09785111, -0.18915492,
#        -0.46471608,  0.50403039,  1.68856579, -1.07596637,  0.45882649,
#        -0.0484962 , -0.14518238, -0.21781261,  1.57233397,  1.08399299,
#         0.1620863 , -0.50621542,  0.93322816,  0.36504563, -0.42499295,
#        -0.406113  ,  0.26988598, -1.65546405, -0.14513967, -0.27679724,
#        -0.56247863,  0.70353559, -0.75766726,  0.23965767, -0.38658618,
#        -0.39118656, -0.48913556,  2.86447484,  0.10288452, -0.8310116 ,
#        -1.60717932, -1.47934754, -0.9878885 , -0.48323367, -0.20036011,
#         1.05275277, -0.48108447,  0.37668157, -0.03049935,  0.60705215,
#         0.50653593,  0.03113915, -0.10187938,  1.96796081,  0.1082362 ,
#        -1.14388703, -0.58296045, -1.6746724 , -0.64892165, -1.47007184,
#         1.02644517,  2.24288362,  0.27689795, -0.7650762 , -0.74665176,
#        -1.2808795 , -1.39528632, -0.25274243,  1.01856503, -0.40034718,
#        -1.77671808,  2.1168332 , -1.90080796,  0.61016291,  1.9165978 ,
#         1.20202153,  0.79170062, -1.97770584,  0.81881606, -0.71446924,
#        -0.01997034, -1.44779772, -1.25097597, -1.0174177 ,  1.91827316,
#        -0.90579617, -1.38363739, -2.4113519 ,  1.82148828,  0.67738264,
#        -0.54184505, -2.45027392, -1.07995635, -0.79394091,  2.04609304,
#        -0.88943491,  0.65949526, -1.72495389, -0.35482445,  1.02366882])


#### 11.10에서 생성한 배열의 평균, 표준편차 출력

In [12]:
# 결과예시
# 평균: -0.03533959537061757
# 표준편차: 1.1267077319752274

In [13]:
print('평균:')
print('표준편차:')

평균:
표준편차:


#### 12. 0에서 1사이 0.01간격의 10x10 배열 생성

In [18]:
# 결과

# array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
#        [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
#        [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
#        [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
#        [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
#        [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
#        [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
#        [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
#        [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
#        [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [17]:
np.arange(0.01, 1.01, 0.01).reshape(10,10)

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

#### 13. 1에서 100사이 균등 간격으로 10개의 숫자 생성

In [15]:
# 결과
# array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

* 아래 배열에서 값을 선택하세요

In [19]:
arr = np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


#### 14

In [17]:
# -----------------------
# arr에서 아래와 같은 값 선택
# -----------------------
print(arr)
# 결과
# array([[12, 13, 14, 15],
#        [17, 18, 19, 20],
#        [22, 23, 24, 25]])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [20]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 15

In [18]:
# -----------------------
# arr에서 아래와 같은 값 선택
# -----------------------

# 결과
# np.int64(20)

In [21]:
arr[3, 4]

np.int64(20)

#### 16

In [19]:
# -----------------------
# arr에서 아래와 같은 값 선택
# -----------------------

# 결과
# array([21, 22, 23, 24, 25])

In [22]:
arr[4, : ]

array([21, 22, 23, 24, 25])

#### 17

In [20]:
# 결과

# -----------------------
# arr에서 아래와 같은 값 선택
# -----------------------

# 결과
# array([[16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25]])

In [24]:
arr
arr[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 18. 전체 합계

In [21]:
# 결과

# -----------------------
# arr의 전체 합계
# -----------------------

# 결과
# np.int64(325)

In [26]:
np.sum(arr)

np.int64(325)

#### 19. 전체 표준편차

In [22]:
# 결과

# -----------------------
# arr의 전체 표준편차
# -----------------------

# 결과
# np.float64(7.211102550927978)

In [32]:
np.std(arr)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325])

#### 20. 열별 합계

In [23]:
# 결과

# -----------------------
# arr의 열별 합계
# -----------------------

# 결과
# array([55, 60, 65, 70, 75])

In [35]:
arr
np.sum(arr, axis=0)

array([55, 60, 65, 70, 75])