In [1]:
import numpy as np

## 배열의 shape 제어

#### `배열객체.reshape()`
* `배열객체.reshape(shape)`
* size의 갯수만 맞다면 자유롭게 shape를 변경할 수 있다.
* -1을 적으면 배열의 size에 맞게 자동으로 갯수가 지정된다.

In [ ]:
arr = np.arange(1,7)
print('arr>>>', arr, '\n')

print('--- 3행 2열로 reshape ---')

print('--- 2행 3열로 reshape ---')

print('--- 6행 1열로 reshape ---')


arr>>> [1 2 3 4 5 6] 

--- 3행 2열로 reshape ---
[[1 2]
 [3 4]
 [5 6]]
--- 2행 3열로 reshape ---
[[1 2 3]
 [4 5 6]]
--- 6행 1열로 reshape ---
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


#### `배열객체.flatten()`
* `배열객체.flatten()`
  * 다차원의 배열을 1차원으로 변경

In [ ]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)
print('-----flatten-----')


[[1 2]
 [3 4]
 [5 6]]
-----flatten-----
[1 2 3 4 5 6]


#### `배열객체.transpose()`

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('-----배열 전치-----')


[[1 2 3]
 [4 5 6]]
-----배열 전치-----
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


## 배열 연결
#### `np.concatenate()`
* `np.concatenate(연결할 배열 리스트, axis=축)`

In [ ]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr3 = np.arange(9,13).reshape(2,2)

print('-- arr1 --\n', arr1, '\n')
print('-- arr2 --\n', arr2, '\n')
print('-- arr3 --\n', arr3, '\n')


print('----- 행 방향으로 concatenate -----')



print('----- 열 방향으로 concatenate -----')


-- arr1 --
 [[1 2]
 [3 4]] 

-- arr2 --
 [[5 6]
 [7 8]] 

-- arr3 --
 [[ 9 10]
 [11 12]] 

----- 행 방향으로 concatenate -----
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
----- 열 방향으로 concatenate -----
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


#### `np.vstack()`
* `np.vstack(연결할 배열리스트)` 
    * 수직방향(vertical) 연결
    * concatenate, axis=0과 동일


In [ ]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr3 = np.arange(9,13).reshape(2,2)
print('-- arr1 --\n', arr1, '\n')
print('-- arr2 --\n', arr2, '\n')
print('-- arr3 --\n', arr3, '\n')

print('----- 수직방향 연결 -----')



-- arr1 --
 [[1 2]
 [3 4]] 

-- arr2 --
 [[5 6]
 [7 8]] 

-- arr3 --
 [[ 9 10]
 [11 12]] 

----- 수직방향 연결 -----


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

#### `np.hstack()` 
* `np.hstack(연결할 배열리스트)`
    * 수평방향(horizontal) 연결 
    * concatenate, axis=1과 동일

In [ ]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr3 = np.arange(9,13).reshape(2,2)

print('-- arr1 --\n', arr1, '\n')
print('-- arr2 --\n', arr2, '\n')
print('-- arr3 --\n', arr3, '\n')

print('----- 수평방향 연결 -----')


-- arr1 --
 [[1 2]
 [3 4]] 

-- arr2 --
 [[5 6]
 [7 8]] 

-- arr3 --
 [[ 9 10]
 [11 12]] 

----- 수평방향 연결 -----


array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

## 배열 분할
#### `np.split()`
* `np.split(배열, 분할할갯수, axis)`
* `np.split(배열, [기준인덱스], axis)`


In [ ]:
arr = np.arange(1,10)
print(arr)

print('----- 3개로 분할 -----')


print('----- 인덱스3 기준으로 분할 -----')


print('----- 인덱스3, 5 기준으로 분할 -----')



[1 2 3 4 5 6 7 8 9]
----- 3개로 분할 -----
[1 2 3]
[4 5 6]
[7 8 9]
----- 인덱스3 기준으로 분할 -----
[1 2 3]
[4 5 6 7 8 9]
----- 인덱스3, 5 기준으로 분할 -----
[1 2 3]
[4 5]
[6 7 8 9]


In [ ]:
arr = np.arange(1, 13).reshape(4,3)
print(arr)

print('-----2개로 분할(axis=0)-----')


print('-----3개로 분할(axis=1)-----')


print('-----인덱스 1 기준으로 분할(axis=0)-----')


print('-----인덱스 1 기준으로 분할(axis=1)-----')


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
-----2개로 분할(axis=0)-----
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
-----3개로 분할(axis=1)-----
[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[[ 3]
 [ 6]
 [ 9]
 [12]]
-----인덱스 1 기준으로 분할(axis=0)-----
[[1 2 3]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
-----인덱스 1 기준으로 분할(axis=1)-----
[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


#### `np.vsplit()` 
* `np.vsplit(배열,[기준인덱스])` 
    * 수직방향 분할

In [ ]:
arr = np.arange(1,13).reshape(4,3)
print(arr)

print('----- 인덱스 1 기준으로 분할 -----')


print('----- 인덱스 1,2 기준으로 분할 -----')


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----- 인덱스 1 기준으로 분할 -----
[[1 2 3]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----- 인덱스 1,2 기준으로 분할 -----
[[1 2 3]]
[[4 5 6]]
[[ 7  8  9]
 [10 11 12]]


#### `np.hsplit()` 
* `np.hsplit(배열,[기준인덱스])` 
    * 수평방향 분할

In [ ]:
arr = np.arange(1,13).reshape(4,3)
print(arr)

print('----- 인덱스 1 기준으로 분할 -----')


print('----- 인덱스 1,2 기준으로 분할 -----')


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----- 인덱스 1 기준으로 분할 -----
[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
----- 인덱스 1,2 기준으로 분할 -----
[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[[ 3]
 [ 6]
 [ 9]
 [12]]
