In [1]:
import numpy as np

## 배열의 shape 제어

#### `배열객체.reshape()`
* `배열객체.reshape(shape)`
* size의 갯수만 맞다면 자유롭게 shape를 변경할 수 있다.
* -1을 적으면 배열의 size에 맞게 자동으로 갯수가 지정된다.

In [2]:
arr = np.arange(1,7)
print(arr)
print('---reshape---')
print(arr.reshape(3,2))
print('---reshape---')
print(arr.reshape(2,3))
print('---reshape---')
print(arr.reshape(6,1))

[1 2 3 4 5 6]
---reshape---
[[1 2]
 [3 4]
 [5 6]]
---reshape---
[[1 2 3]
 [4 5 6]]
---reshape---
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


#### `배열객체.flatten()`
* `배열객체.flatten()`
  * 다차원의 배열을 1차원으로 변경

In [3]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)
print('-----flatten-----')
print(arr.flatten())

[[1 2]
 [3 4]
 [5 6]]
-----flatten-----
[1 2 3 4 5 6]


#### `배열객체.transpose()`

In [4]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('-----배열 전치-----')
print(arr.transpose())
print('-----배열 전치-----')
print(arr.T)

[[1 2 3]
 [4 5 6]]
-----배열 전치-----
[[1 4]
 [2 5]
 [3 6]]
-----배열 전치-----
[[1 4]
 [2 5]
 [3 6]]


#### `배열객체.resize()`
* `배열객체.resize(배열크기)`
    * 기존 배열보다 사이즈가 크면 0으로 채움
    * 기존 배열보다 사이즈가 작으면 포함되지 않은 값은 삭제됨

In [5]:
arr = np.array([[0, 1], [2, 3]])
print(arr)
print('-----resize-----')
arr.resize((3,3))
print(arr)
print('-----resize-----')
arr.resize((2,1))
print(arr)

[[0 1]
 [2 3]]
-----resize-----
[[0 1 2]
 [3 0 0]
 [0 0 0]]
-----resize-----
[[0]
 [1]]


## 배열 연결
#### `np.concatenate()`
* `np.concatenate(연결할 배열 리스트, axis=축)`

In [6]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr3 = np.arange(9,13).reshape(2,2)
print(arr1)
print('----------')
print(arr2)
print('----------')
print(arr3)
print('---- concat:axis=0 -----')
print(np.concatenate([arr1,arr2,arr3], axis=0))
print('---- concat:axis=1 -----')

print(np.concatenate([arr1,arr2,arr3], axis=1))

[[1 2]
 [3 4]]
----------
[[5 6]
 [7 8]]
----------
[[ 9 10]
 [11 12]]
---- concat:axis=0 -----
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
---- concat:axis=1 -----
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


#### `np.vstack()`
* `np.vstack(연결할 배열리스트)` 
    * 수직방향(vertical) 연결
    * concatenate, axis=0과 동일


In [7]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr3 = np.arange(9,13).reshape(2,2)
print(arr1)
print('----------')
print(arr2)
print('----------')
print(arr3)

np.vstack([arr1,arr2,arr3])

[[1 2]
 [3 4]]
----------
[[5 6]
 [7 8]]
----------
[[ 9 10]
 [11 12]]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

#### `np.hstack()` 
* `np.hstack(연결할 배열리스트)`
    * 수평방향(horizontal) 연결 
    * concatenate, axis=1과 동일

In [8]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr3 = np.arange(9,13).reshape(2,2)
print(arr1)
print('----------')
print(arr2)
print('----------')
print(arr3)

np.hstack([arr1,arr2,arr3])

[[1 2]
 [3 4]]
----------
[[5 6]
 [7 8]]
----------
[[ 9 10]
 [11 12]]


array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

## 배열 분할
#### `np.split()`
* `np.split(배열, 분할할갯수, axis)`
* `np.split(배열, [기준인덱스], axis)`


In [9]:
arr = np.arange(1,10)
print(arr)

print('----- 3개로 분할 -----')
arr1, arr2, arr3 = np.split(arr, 3)
print(arr1)
print(arr2)
print(arr3)

print('----- 인덱스3 기준으로 분할 -----')
arr1, arr2 = np.split(arr,[3])
print(arr1)
print(arr2)

print('----- 인덱스3, 5 기준으로 분할 -----')
arr1, arr2, arr3 = np.split(arr,[3, 5])
print(arr1)
print(arr2)
print(arr3)


[1 2 3 4 5 6 7 8 9]
----- 3개로 분할 -----
[1 2 3]
[4 5 6]
[7 8 9]
----- 인덱스3 기준으로 분할 -----
[1 2 3]
[4 5 6 7 8 9]
----- 인덱스3, 5 기준으로 분할 -----
[1 2 3]
[4 5]
[6 7 8 9]


In [13]:
arr = np.arange(1, 13).reshape(4,3)
print(arr)

print('-----2개로 분할(axis=0)-----')
arr1, arr2 = np.split(arr, 2)
print(arr1)
print(arr2)

print('-----3개로 분할(axis=1)-----')
arr1, arr2, arr3 = np.split(arr, 3, axis=1)
print(arr1)
print(arr2)
print(arr3)

print('-----인덱스 1 기준으로 분할(axis=0)-----')
arr1, arr2 = np.split(arr, [1])
print(arr1)
print(arr2)

print('-----인덱스 1 기준으로 분할(axis=1)-----')
arr1, arr2 = np.split(arr, [1], axis=1)
print(arr1)
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
-----2개로 분할(axis=0)-----
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
-----3개로 분할(axis=1)-----
[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[[ 3]
 [ 6]
 [ 9]
 [12]]
-----인덱스 1 기준으로 분할(axis=0)-----
[[1 2 3]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
-----인덱스 1 기준으로 분할(axis=1)-----
[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


#### `np.vsplit()` 
* `np.vsplit(배열,[기준인덱스])` 
    * 수직방향 분할

In [14]:
arr = np.arange(1,13).reshape(4,3)
print(arr)

print('----- 인덱스 1 기준으로 분할 -----')
arr1, arr2 = np.vsplit(arr,[1])
print(arr1)
print(arr2)

print('----- 인덱스 1,2 기준으로 분할 -----')
arr1, arr2, arr3 = np.vsplit(arr,[1,2])
print(arr1)
print(arr2)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----- 인덱스 1 기준으로 분할 -----
[[1 2 3]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----- 인덱스 1,2 기준으로 분할 -----
[[1 2 3]]
[[4 5 6]]
[[ 7  8  9]
 [10 11 12]]


#### `np.hsplit()` 
* `np.hsplit(배열,[기준인덱스])` 
    * 수평방향 분할

In [15]:
arr = np.arange(1,13).reshape(4,3)
print(arr)

print('----- 인덱스 1 기준으로 분할 -----')
arr1, arr2 = np.hsplit(arr,[1])
print(arr1)
print(arr2)

print('----- 인덱스 1,2 기준으로 분할 -----')
arr1, arr2, arr3 = np.hsplit(arr,[1,2])
print(arr1)
print(arr2)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----- 인덱스 1 기준으로 분할 -----
[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
----- 인덱스 1,2 기준으로 분할 -----
[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[[ 3]
 [ 6]
 [ 9]
 [12]]
