# pytorch - 2025년 9월 23일

# tensor

In [1]:
# python list를 tensor로
import torch

list_data = [[10, 20], [30, 40]]
t1 = torch.Tensor(list_data)

print(type(list_data))
print(type(t1))
print(t1.shape)
print(t1.dtype)

<class 'list'>
<class 'torch.Tensor'>
torch.Size([2, 2])
torch.float32


In [2]:
import numpy as np

list_data = [[10, 20], [30, 40]]
n1 = np.array(list_data)
t1 = torch.Tensor(n1)
print(n1)
print(t1)

[[10 20]
 [30 40]]
tensor([[10., 20.],
        [30., 40.]])


In [3]:
# 랜덤데이터 -> 텐서
t3 = torch.rand(2,2)
print(t3)
print(t3.shape)

t4 = torch.randn(2,2)
print(t4)
print(t4.shape)

tensor([[0.9689, 0.6887],
        [0.9295, 0.9248]])
torch.Size([2, 2])
tensor([[0.1379, 1.1899],
        [0.5283, 0.8372]])
torch.Size([2, 2])


In [4]:
#텐서의 연산
t5 = torch.Tensor([[1,2,3], [4,5,6]])
t6 = torch.Tensor([[7,8,9], [10,11,12]])

print(t5)
print(t6)
print(t5[0])
print(t6[:, 1:])
print(t6[0:2, 0:-1])
print(t6[-1, -1])
print(t6[..., -1]) #...은 모든 차원을 의미

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([1., 2., 3.])
tensor([[ 8.,  9.],
        [11., 12.]])
tensor([[ 7.,  8.],
        [10., 11.]])
tensor(12.)
tensor([ 9., 12.])


In [5]:
t8 = t5.mul(t6)
print(t8)

tensor([[ 7., 16., 27.],
        [40., 55., 72.]])


In [6]:
#행렬곱, A의 행렬의 행과 B행렬의 열이 같아야 함

t9 = t5.view(3,2)
t8 = t9.matmul(t6)
print(t8)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [7]:
# 텐서 합치기
t5 = torch.Tensor([[1,2,3]])
t10 = torch.cat([t5,t6], dim=0)
print(t10)

tensor([[ 1.,  2.,  3.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
1 인공신경망 절차
  1. 데이/터 불러오기
  2. X(독립변수), y(종속변수, 정답, 레이블) 분리
  3. 정규화
  4. 텐서로 변환
  5. 훈련 /테스트 데이터 분할
  6. 클래스 기반 모델 정의, 모델생성
  7. 손실함수 & 옵티마이저
  8. 학습하기
  9. 평가하기

SyntaxError: invalid syntax (1027927874.py, line 1)

In [9]:
# 1. 데이터 가져오기
import torch
from torch import nn
# 2. X(독립변수), y(종속변수, 정답, 레이블) 분리
x_train = torch.Tensor([1,2,3,4,5,6,7,8,9,10]).view(10,1)
y_train = torch.Tensor([3,4,5,6,7,8,9,10,11,12]).view(10,1)

print(x_train)
print(y_train)

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
tensor([[ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]])


In [10]:
from torch.utils.data import DataLoader, TensorDataset 
dataset = TensorDataset(x_train, y_train)
dataloader = DataLoader(dataset, batch_size = 2, shuffle=True)

In [32]:
# 6. 모델 구축
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,8)

    def forward(self, x):
        return self.linear(x)

model = MyModel()

In [33]:
# 7. 손실함수 & 옵티마이저
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [34]:
# 8. 학습하기
epochs = 100

for epoch in range(epochs):
    model.train()

    for batch_x, batch_y in dataloader:
        prediction = model(batch_x)
        loss = criterion(batch_y, prediction)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    if epoch % 2 == 0:
        print(epoch, loss.item())


0 46.689857482910156
2 4.8722639083862305
4 1.8487135171890259
6 1.0599764585494995
8 0.1064542606472969
10 1.4570868015289307
12 1.3753249645233154
14 0.18162497878074646
16 0.9270771741867065
18 0.9146040678024292
20 0.4536735415458679
22 1.001062273979187
24 0.19914329051971436
26 0.38455358147621155
28 0.1891619861125946
30 1.5140031576156616
32 0.1349017471075058
34 0.6038120985031128
36 0.675733208656311
38 0.44285646080970764
40 1.1612193584442139
42 0.912674605846405
44 0.11842738091945648
46 1.1260051727294922
48 0.7951262593269348
50 0.36274254322052
52 0.5541219115257263
54 1.5356525182724
56 0.1227802261710167
58 1.3228201866149902
60 0.1377602219581604
62 1.2756990194320679
64 0.7310805320739746
66 0.5417509078979492
68 0.31402793526649475
70 0.14469413459300995
72 0.6723095774650574
74 0.8996928334236145
76 0.2634078860282898
78 0.7524065375328064
80 0.5147157907485962
82 0.0534016415476799
84 0.9234654903411865
86 0.3245072662830353
88 0.2500056326389313
90 0.50667303800

c:\Users\edukd\miniconda3\envs\myKDA2\Lib\site-packages\torch\nn\modules\loss.py:610: UserWarning: Using a target size (torch.Size([2, 8])) that is different to the input size (torch.Size([2, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [35]:
model.eval()
torch.no_grad()
x_test = torch.Tensor([7,8,9,10]).view(4,1)
pred = model(x_test)
print(pred)

tensor([[ 9.0054,  9.0042,  9.0077,  9.0070,  9.0054,  9.0052,  9.0032,  9.0039],
        [10.2175, 10.1689, 10.3125, 10.2831, 10.2173, 10.2125, 10.1301, 10.1582],
        [11.4295, 11.3336, 11.6172, 11.5593, 11.4292, 11.4197, 11.2570, 11.3124],
        [12.6416, 12.4983, 12.9220, 12.8354, 12.6411, 12.6270, 12.3840, 12.4667]],
       grad_fn=<AddmmBackward0>)


In [36]:
# 가중치 확인
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[1.2121],
        [1.1647],
        [1.3048],
        [1.2761],
        [1.2119],
        [1.2072],
        [1.1269],
        [1.1543]], requires_grad=True)
Parameter containing:
tensor([ 0.5207,  0.8512, -0.1256,  0.0740,  0.5219,  0.5545,  1.1148,  0.9241],
       requires_grad=True)


In [37]:
print(model)

MyModel(
  (linear): Linear(in_features=1, out_features=8, bias=True)
)


# 클래스

In [17]:
class Car :
    def __init__(self, brand, model, color):
        self.brand = brand
        self.model = model
        self.color = color
    def turn_on(self):
        print(self.brand, "turn on")
    def turn_off(self):
        print(self.brand, "turn off")

my_car = Car("kia", 'k5', 'red')
your_car = Car('hyndai', 'genesis', 'black')

my_car.turn_on()
your_car.turn_off()

kia turn on
hyndai turn off


In [18]:
class Mom :
    def __init__(self, name):
        self.name = name
    def cook(self):
        print("cook")
class Me(Mom):
    def __init__(self, myname, name):
        super().__init__(name)
        self.myname = myname
        self.name = name
    def study(self):
        print(self.myname, self.name, "열심히 공부하자")

me = Me("홍길동", "엄마")
me.study()

홍길동 엄마 열심히 공부하자
