## 2.1 넘파이 소개

In [79]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [80]:
import numpy as np 

data = [1, 2, 3]
arr = np.array(data)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [81]:
data = [1, 2, 3]

result = []
for i in data:
    result.append(i * 10)

print(result)

[10, 20, 30]


In [82]:
import numpy as np

arr = np.array([1, 2, 3])  # numpy.ndarray 수치 연산에 강한 data type
result = arr * 10
print(result)

[10 20 30]


In [83]:
data2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(data2d[2][1])
# 튜플 ()  -> ()  박물관에 전시된 전시품
# 리스트 [] - append del, pop 즉 과일바구니 딕셔너리 {키:값} -> [] 사물함   

8


In [84]:
import numpy as np

arr = np.array(data2d)
print(arr[:, 0])

[1 4 7]


## 2.2 ndarray

In [85]:
data1 = [1, 2, 3, 4]
print(data1)
print(type(data1))
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [86]:
data2 = [
    [1, 2],
    [3, 4]
]
arr2 = np.array(data2)

print(arr2)
print(type(arr2))
print(type(arr2[1,1]))
print(type(arr2[0]))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.ndarray'>


In [87]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

(2, 2)
2
int64


In [88]:
print(arr1.shape)

(4,)


In [89]:
arr1

array([1, 2, 3, 4])

In [90]:
data = [
    [1],
    [2],
    [3],
    [4]
]

c = np.array(data)
print(c.shape)

(4, 1)


In [91]:
print(np.zeros(3))
print(np.ones(3))

[0. 0. 0.]
[1. 1. 1.]


In [92]:
size = (3, 4)
print(np.zeros(size))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [93]:
print(np.zeros((3, 4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [94]:
print(np.arange(5))
print(np.arange(1, 5))
print(np.arange(1, 5, 2))

[0 1 2 3 4]
[1 2 3 4]
[1 3]


In [95]:
# 어떤 주식의 5일간 종가
# 하루 수익률 (오늘 가격 - 어제 가격) / 어제 가격
# 종가, 하루 수익률, 평균 수익률, 변동성(표준편차)
price = [100, 102, 98, 105, 110]
yesterday_price = [100]
day_profitrate = []
profit_sum = 0
for i in range(4):
    yesterday_price.append(price[i])
for i in range(5):
    print(f"{i+1}일째 종가는 {price[i]}이다.")
    print(f"{i+1}일째 수익률은 {round((price[i]-yesterday_price[i]) / yesterday_price[i] * 100, 2)}%이다.")
    day_profitrate.append(round((price[i]-yesterday_price[i]) / yesterday_price[i] * 100, 2))
    profit_sum += round((price[i]-yesterday_price[i]) / yesterday_price[i] * 100, 2)
print(f"평균 수익률은 {profit_sum / len(price)}%이다.")
print(round(np.average(day_profitrate),2))
print(f"변동성은 {np.std(day_profitrate)}이다.")


1일째 종가는 100이다.
1일째 수익률은 0.0%이다.
2일째 종가는 102이다.
2일째 수익률은 2.0%이다.
3일째 종가는 98이다.
3일째 수익률은 -3.92%이다.
4일째 종가는 105이다.
4일째 수익률은 7.14%이다.
5일째 종가는 110이다.
5일째 수익률은 4.76%이다.
평균 수익률은 1.996%이다.
2.0
변동성은 3.823179828362773이다.


## 2.3 데이터 타입

In [96]:
arr = np.array([1, 2, 3], dtype=np.uint8)
print(arr.dtype)
print(arr.dtype.kind)
print(arr.dtype.alignment)

uint8
u
1


In [97]:
arr = arr.astype('int8')
print(arr.dtype)

int8


In [98]:
a = np.array([0, 255], dtype=np.uint8)
b = a.astype('int8')
print(a)
print(b)

[  0 255]
[ 0 -1]


In [99]:
a16 = np.array([1.333333], dtype=np.float16)
a32 = np.array([1.333333], dtype=np.float32)
print(a16)
print(a32)

[1.333]
[1.333333]


In [100]:
a16 = np.array([1.0], dtype=np.float16)
a32 = np.array([1.0], dtype=np.float32)
print(a16/3)
print(a32/3)

[0.3333]
[0.33333334]


In [101]:
print(np.nan, type(np.nan))
print(np.inf, type(np.inf))
print(-np.inf, type(-np.inf))

nan <class 'float'>
inf <class 'float'>
-inf <class 'float'>


In [102]:
arr = np.array([-1, 2, -3])
print(arr/0)

[-inf  inf -inf]


C:\Users\edukd\AppData\Local\Temp\ipykernel_21988\4227457732.py:2: RuntimeWarning: divide by zero encountered in divide
  print(arr/0)


In [103]:
arr = np.array([-1, 2, -3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


## 2.4 인덱싱과 슬라이싱

In [104]:
arr = np.arange(4)
print(arr[0])

0


In [105]:
arr = np.arange(4).reshape(2, 2)
print(arr[0])

[0 1]


In [106]:
print(arr[0][0])

0


In [107]:
print(arr[0][0])
print(arr[0, 0])

0
0


In [108]:
a = np.arange(10000).reshape(100, 100)
%timeit a[0, 50]

141 ns ± 45.5 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [109]:
a = np.arange(10000).reshape(100, 100)
%timeit a[0][50]

253 ns ± 33.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [110]:
arr = np.arange(4)
print(arr[:2])

[0 1]


In [111]:
target = [0, 2]
print(arr[target])

[0 2]


In [112]:
print(arr[ [0, 2] ])

[0 2]


In [113]:
arr = np.arange(20).reshape(4, 5)
print(arr[:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [114]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [117]:
arr[2,3]
arr[2][3]

np.int64(13)

In [53]:
result = []
for row in arr:
    row_01 = [row[0], row[1]]
    result.append(row_01)

print(result)

[[0, 1], [5, 6], [10, 11], [15, 16]]


In [54]:
print(arr[:, :2])

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]


In [55]:
print(arr[1:4, 2:5])
print(arr[1:, 2:])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


## 브로드캐스팅

In [9]:
import numpy as np

data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# TODO: 전체 합계 구하기
print(np.sum(data))
# TODO: 행 방향(axis=1) 합계 구하기
print(np.sum(data, axis=1))
# TODO: 열 방향(axis=0) 평균 구하기
print(np.mean(data, axis=0))
print(data.ndim)
print(data.size)
print(data.shape)

45
[ 6 15 24]
[4. 5. 6.]
2
9
(3, 3)


In [11]:

scores = np.array([
    [90, 80, 85],
    [70, 75, 80],
    [60, 65, 70]
])

score_mean = np.mean(scores)  #  평균
print(score_mean)
score_std = np.std(scores)   #  표준편차

broadcasted = (scores - score_mean) / score_std
np.mean(broadcasted, axis=1)
np.std(broadcasted, axis=0)

75.0


array([1.3662601 , 0.68313005, 0.68313005])

In [56]:
a = np.array( [1, 2, 3] )
b = np.array( [2, 3, 4] )
print(a + b)
print(a * b)
print(a % b)

[3 5 7]
[ 2  6 12]
[1 2 3]


In [57]:
print(a + 3)

[4 5 6]


In [58]:
high = [92700, 92400, 92100, 94300, 92300]
low = [90000, 91100, 91700, 92100, 90900]

arr_high = np.array(high)
arr_low = np.array(low)

arr_diff = arr_high - arr_low
print(arr_diff)

[2700 1300  400 2200 1400]


In [60]:
arr_high_x3 = arr_high * 3
arr_low_x2 = arr_low * 2
print(arr_high_x3 + arr_low_x2)

[458100 459400 459700 467100 458700]


In [61]:
avg = (arr_high * 3) + arr_low * 2

In [62]:
data = [
    [92700, 92400, 92100, 94300, 92300],
    [90000, 91100, 91700, 92100, 90900]
]
arr = np.array(data)

In [63]:
print(arr[0] * 3 + arr[1]  * 2)

[458100 459400 459700 467100 458700]


In [64]:
weight = np.array([3, 2]).reshape(2, 1)

In [66]:
print((weight * arr).sum(axis=0))

[458100 459400 459700 467100 458700]


## 2.6 조건 연산

In [12]:
arr = np.array( [10, 20, 30] )
print(arr > 10)

[False  True  True]


In [13]:
arr = np.array([10, 20, 30])
cond = [False, True, True]
print(arr[ cond ])

[20 30]


In [14]:
arr = np.array([10, 20, 30])
print(arr[[False, True, True] ])

[20 30]


In [15]:
arr = np.array([10, 20, 30])
cond = arr > 10
print(arr[ cond ])

[20 30]


In [16]:
print(arr[ arr > 10 ])

[20 30]


In [17]:
cond.all()

np.False_

In [18]:
cond.any()

np.True_

In [19]:
arr = np.array([10, 20, 30])
cond0 = arr > 10
cond1 = arr < 30
print(arr[ cond0 & cond1 ])

[20]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
list = [True, False, True, False, True]

# TODO: 20보다 큰 값 고르기
cond0 = arr > 20
print(arr[cond0])
# TODO: 짝수만 고르기
cond1 = arr % 2 == 0
print(arr[cond1])
# TODO: 15 이상 40 이하 값 고르기
cond = arr >= 15
cond1 = arr <= 40
print(arr[cond & cond1])
# TODO: 30이 아닌 값 고르기
cond = arr != 30
print(arr[cond])
# TODO: 조건 리스트(cond) 사용해 고르기
print(arr[list])



[30 40 50]
[10 20 30 40 50]
[20 30 40]
[10 20 40 50]
[10 30 50]


In [40]:

import pandas as pd

s = pd.Series([5, 10, 15, 20, 8])


# 1) 조건: 값이 10보다 크면 10을 더하고, 아니면 -10을 빼기
# TODO: np.where 또는 map 을 활용해 구현해보세요.
result = np.where(s > 10, s + 10, s - 10)
print(result)

# 2) 조건: 값이 짝수면 그대로 두고, 홀수면 0으로 바꾸기
# TODO: 조건 연산으로 만들어보세요.
even_only = np.where( s % 2 == 0, s, 0)
print(even_only)

# 3) 조건: 평균보다 크면 "HIGH", 작으면 "LOW"라는 문자열로 바꾸기
# TODO: map 또는 list comprehension을 활용해보세요.
labels = ["HIGH" if x > np.mean(s) else "LOW" for x in s]
print(labels)


[-5  0 25 30 -2]
[ 0 10  0 20  8]
['LOW', 'LOW', 'HIGH', 'HIGH', 'LOW']


In [75]:
arr = np.array([10, 20, 30])
print(arr[ (arr > 10) & (arr < 30) ])

[20]


In [76]:
arr = np.array([10, 20, 30])
cond = arr > 10
arr[cond] = 1
arr[~cond] = 0
print(arr)

[0 1 1]


In [77]:
arr = np.array([10, 20, 30])
arr = np.where( arr > 10, 1, 0)
print(arr)

[0 1 1]


In [79]:
cond = arr > 10
arr[cond] = arr[cond] + 10
arr[~cond] = arr[~cond] - 10

In [80]:
arr

array([-10,  -9,  -9])

In [82]:
arr = np.array([10, 20, 30])
arr = np.where( arr > 10, arr+10, arr-10)
print(arr)

[ 0 30 40]


In [83]:
lge = np.array([93000, 82400, 99100, 81000, 72300])
result = lge[  lge <= 85000  ]
print( len(result) )

3


## 함수와 메서드

In [52]:
import numpy as np

# 1) 0부터 7까지 정수 배열을 만들고, (4행 2열)로 모양을 바꾸세요.
arr = np.arange(8).reshape(4,2)
print("arr:\n", arr)

# 2) 0 이상 46 미만 정수 중에서 랜덤하게 5개 뽑아보세요.
rand_nums = np.random.randint(46, size=5)
print(rand_nums)

# 3) 0부터 10까지를 3등분한 배열을 만들어보세요. (힌트: linspace)
x = np.linspace(0, 10, 3)
print(x)

# 4) arr 배열에서 모든 원소의 합과 평균을 각각 구해보세요.
arr_sum = arr.sum()
arr_mean = arr.mean()
print(arr_sum)
print(arr_mean)

# 5) arr 배열의 행별 합(axis=1)을 구해보세요.
row_sum = arr.sum(axis=1)
print(row_sum)



arr:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
[41  3 29 32 34]
[ 0.  5. 10.]
28
3.5
[ 1  5  9 13]


In [84]:
arr = np.arange(8).reshape(4, 2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [85]:
print(arr.sum())

28


In [86]:
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[12 16]
[ 1  5  9 13]


In [43]:
np.random.randint(3)

1

In [44]:
np.random.randint(46, size=5)

array([31,  0, 24, 29,  4], dtype=int32)

In [45]:
np.random.randint(46, size=(2, 5))

array([[13,  7, 42,  3, 38],
       [ 0,  9, 29,  2, 19]], dtype=int32)

In [50]:
x = np.linspace(0, 10, 3)
print(x)

[ 0.  5. 10.]


In [92]:
y = x ** 2

In [93]:
y

array([  0.,  25., 100.])

In [53]:
a = np.arange(4)
b = np.arange(4, 8)
c = np.vstack([a, b])
print(c)

[[0 1 2 3]
 [4 5 6 7]]


In [54]:
np.hstack([a, b])

array([0, 1, 2, 3, 4, 5, 6, 7])